exports.ADD_OWNER = 'ADD_OWNER';
exports.REFRESH_USERS = 'REFRES_USERS';
exports.UPDATE_USER_TYPE = 'UPDATE_USER_TYPE';
exports.UPDATE_USER_NAME = 'UPDATE_USER_NAME';
exports.UPDATE_USER = 'UPDATE_USER';
exports.UPDATE_QUEUES = 'UPDATE_QUEUES';